### ISSUE TITLE
Mavericks builds fail

### ISSUE THREAD

**Issue by dgoodlad** [boxen/puppet-qt#4]
This issue is simply to help track what's going on in homebrew-land to fix qt builds on Mavericks.
- mxcl/homebrew#23793 fixed the build but requires `--HEAD`
- mxcl/homebrew#24674 uses a specific qt 4.8 revision, and seems to be where homebrew is heading until qt make a patch release in January

**Comment by owenthereal** [comment]
I've seen the homebrew master [has fixed the problem](https://github.com/Homebrew/homebrew/pull/23793).

**Comment by owenthereal** [comment]
See https://github.com/boxen/puppet-qt/pull/5
